### PR TITLE
Proto Plugins

### PR DESCRIPTION
**Pull request by Damian-P**
Adds plugin support to the actor system

### CODE REVIEW

**Comment by rogeralsing** [comment]
And the plugin system is basically a state store attached to the ActorSystem, so that other parts of the system can ask for a specific plugin?

**Comment by alexeyzimarev** [comment]
Would be nice to have some /// comments there. Otherwise, it's hard to understand what is it.

**Comment by Damian-P** [comment]
Yes it's right, it's state store.

We can do extensions like this :

```csharp
        public static void StartRemote(this ActorSystem actorSystem)
        {
            var remote = actorSystem.Plugins.GetPlugin<IRemote>();
            remote.Start();
        }
        public static IRemote GetRemote(this ActorSystem actorSystem)
        {
            var remote = actorSystem.Plugins.GetPlugin<IRemote>();
            return remote;
        }

```
https://github.com/AsynkronIT/protoactor-dotnet/issues/411#issuecomment-601091505

**Comment by Damian-P** [comment]
We can also use the Microsoft Dependency injection layer instead.

**Comment by alexeyzimarev** [comment]
I am wondering if it is maybe too weak of abstraction? Also, it the actor system who depends on Remote or the other way around?

**Comment by rogeralsing** [comment]
I'm on the fence with this one.
I get the idea, Akka has the Extended Actor System concept which is basically the same.

One of the things I personally have felt pretty good about with Proto.Actor is that it has a simple DI based design.

Remote uses System
Cluster uses Remote

There are some back and forth things in the cluster infra though.

Having registered plugins might in the end lead to design choices where one plugin asks for another.
Another consideration, I'd like to be able to keep the structure at least somewhat similar in the Go impl and other langs.

**Pull request closed without merging**
