### PR TITLE
Separate mailbox project

### PR DESCRIPTION
**Pull request by cpx86**
Just an initial stab at it, splitting off the mailbox, queues and dispatcher into a separate lib. If we want to make this into something more generic, we should think about how we want the API surface of Proto.Mailbox to look. E.g. currently we have a concept of user vs. system messages which makes sense in an actor context, but might not in other contexts.

### CODE REVIEW

**Comment by rogeralsing** [comment]
This needs rebasing

**Comment by cpx86** [comment]
Yep. Will fix the conflicts asap.

**Comment by cpx86** [comment]
There we go :)

**Comment by rogeralsing** [comment]
whoop whoop

**Pull request merged**
