### PR TITLE
Allow client resolvers

### PR DESCRIPTION
**Pull request by sudsy**
## Description

I am expecting to have some time to work on the client project #444 again in the coming months and want to implement the changes in the core that will enable the work to progress.

In the end I decided that a client resolver collection would be the best way to deal with clients. This will permit clients to be registered with the actor system in the same way as remotes are registered.

Clients can be addressed with a scheme like:

 {
            address: "{clienthostaddress}",
            Id: "$client/{guid}/$2"
 }

The rest of the cluster does not need to know that it is communicating with a client.

## Purpose
This pull request is a:

- [x] New feature (non-breaking change which adds functionality)

## Checklist

- [x] I have added tests that prove my fix is effective or that my feature works

### CODE REVIEW

**Comment by rogeralsing** [comment]
Can you elaborate on this one?
When you say client, you mean another remote node?

For cluster we can spawn up nodes that can communicate with the cluster, while not joining themselves.
e.g.
Cluster.StartClientAsync() vs Cluster.SpawnMemberAsync()

Is this change part of making it possible to call back w/o opening a backwards connection to the calling client?

**Comment by sudsy** [comment]
Yes It is part of making it possible to call back w/o opening a backwards connection to the calling client?

Perhaps we need different terminology here but for now I will use the following definitions.

ClientHost - an actor system that can accept client connections without a backwards connection to the calling client.

Client - a calling client that is connected to the ClientHost

The flow will go something like this:

- ClientHost is started just like a normal remote but it has an additional grpc service for accepting Client connections that is started on a different port (ClientHostProxy Port)

- Client connects to ClientHost Proxy Port, client is issued a guid and clientHost registers a clienthostresolver that will handle any messages addressed to:

{
address: "{clienthostaddress}",
Id: "$client/{guid}/*"
}

I have included * in the id above to indicate that it will handle anything that starts with $client/{guid}/

- The root context on the client is given the Id 

{
address: "{clienthostaddress}",
Id: "$client/{guid}/"
}

so that all actors on the client have an address of the form listed above

- When a client communicates with any other node, it always does so through this client proxy connection, with the ClientHost forwarding the messages to the destination.

- When other nodes send a message back to a client actor, they are unaware that they are sending to a client, the just send their messages to the clienthostaddress and the clienthostresolver collection takes care of mapping the ids to the correct client proxy connection.

**Comment by rogeralsing** [comment]
Thanks for the explanation,
So:
```
address: "{clienthostaddress}",
Id: "$client/{guid}/"
```

the `$client/guid` part is used to match that this is should be looked up by the clienthost resolver, correct?

What if we remove that part, and instead have something in the address instead?
That way it should be possible to resolve this via the HostResolvers, just like the remoting layer does.

Address: "client://352353532@192.168.0.232"
Id: "MyActor"

something like that.

Also, the guid, why is that needed if the client has an address?
is it to disambiguate a restarted client that happens to be on the same host+port as a previous client?

**Comment by sudsy** [comment]
IMHO an addressing scheme like Address: "client://352353532@192.168.0.232" looks more logical but I have some concerns about it. All nodes participating in the cluster would need to be aware of the addressing scheme. So, would need to have a host resolver on every single node to handle the resolution of the client:// scheme or some hardcoded awareness of the client:// scheme that re-routes the request to the appropriate client host. Each of the other implementations of protoactor would also need to be aware of the scheme too.

If we were going to make a change in all implementations, I would be in favour of a scheme like:

```
Address: "client://{guid}"
Id: "MyActor"
```
With the lookup of the client location to be handled by a directory (or maybe piggyback on some of the cluster directory functionality). That way, we could handle clients being disconnected and reconnecting to a different clienthost without changing the identity of the actors on the client.

While I am in favour of an approach like this, it's a bigger project than I had in mind for the coming months but I would be happy to work with someone on it.

An implementation like
```
address: "{clienthostaddress}",
Id: "$client/{guid}/"
```
is just the lightest touch implementation that I could come up with. The strength of this approach being that it is a simple implementation, the weakness of this approach is handling client's reconnecting to different clienthosts. (It could still be done, but it is a bit messy)

The reason for using a guid instead of something like 352353532 is so that the client can create it's own guid for an identity without having to request it's identity from the clienthost. The guid saves some startup time for the client (not mutch) but makes for bigger pids with a long guid instead of an integer identifier. I would be happy with either approach really.

**Comment by rogeralsing** [comment]
I'm following now. I'm just dense.

```
{
address: "{clienthostaddress}", 
Id: "$client/{guid}/*"
}
```

In this case, the address is the address of the member node that received the client connection, correct?
So all other nodes only knows about this normal node, and any response to such pid would go to the the node that knows about the client, and this node would then send it back to the correct client.

This is actually brilliant!

**Comment by rogeralsing** [comment]
I'm merging this in :-)

**Comment by sudsy** [comment]
Yeah, that's correct. 

Thanks for the merge, glad to hear you like the approach.

**Pull request merged**
