### PR TITLE
Mutable Message in middlewares

### PR DESCRIPTION
**Pull request by jrouaix**
Made MessageEnvelope mutable to enable receive & sender middlewares to change the message.

### CODE REVIEW

**Comment by jrouaix** [comment]
Come on ! Tired CI !

**Comment by rogeralsing** [comment]
cc @jrouaix conflict

**Comment by jrouaix** [comment]
Yep, now the PR #400 is merged, there could be some. I'll correct that very quickly.

**Comment by jrouaix** [comment]
Ready @rogeralsing.

**Pull request merged**
