### PR TITLE
Made Async: system message processing in LocalContext and HandleFailu…

### PR DESCRIPTION
**Pull request by adamhathcock**
…re in Supervision.

Related to https://github.com/AsynkronIT/protoactor-dotnet/pull/208 and https://github.com/AsynkronIT/protoactor-dotnet/issues/197

### CODE REVIEW

**Comment by tomliversidge** [comment]
You can squash that "oops" commit by doing (on the branch) 
`git rebase -i HEAD~2`

then selecting `f` for fixup on the oops commit.

then do 

`git push --force`

**Comment by adamhathcock** [comment]
Done.  I usually hate rewriting history.

**Comment by tomliversidge** [comment]
I usually do it when on my own branch and no-one else is working on it, as I prefer a single commit to implement something - it makes it easier to read the history and cherry-pick / revert if ever needed (which admittedly is rare, but when you need to it can be awful to go through a bad history...)

One other thing I noticed is there is 

```
private void HandleRootFailure(Failure failure)
        {
            Supervision.DefaultStrategy.HandleFailure(this, failure.Who, failure.RestartStatistics, failure.Reason);
        }
```

which also presumably needs async-ifying?

**Comment by rogeralsing** [comment]
Under what conditions would we need to await the supervisor?
When a child actor fails, it will be suspended, the failure is then escalated to the parent.
The parent handles the failure using its supervisor strategy.
This don't really need to be awaited by the parent actor, it could simply branch off and do it's own thing.

e.g. in the ExponentialBackoffStrategy, the supervisor could await in it's own task, separate from the actor.

if the actor awaits, this means that the parent actor cannot do anything while awaiting the supervisor.

**Comment by adamhathcock** [comment]
Don't need this as any timer that delays actions will NOT be awaited

**Pull request closed without merging**
