### PR TITLE
WIP : OpenTracing support

### PR DESCRIPTION
**Pull request by jrouaix**
Chat example is instrumented with jager tracing.
You can start a jaeger instance with docker : https://www.jaegertracing.io/docs/getting-started/

image

### CODE REVIEW

**Comment by rogeralsing** [comment]
This is amazing! :-)
This will help so much for everyone building actor systems.

Does it also work locally on a single node, just to visualize actor interaction.

I also think, if we do this right, it could become extremely valuable for the cluster support.
To understand what is actually going on

**Comment by jrouaix** [comment]
> Does it also work locally on a single node, just to visualize actor interaction.

It should, will confirm asap.

**Comment by rogeralsing** [comment]
should we merge and work on details in another pr?

**Comment by jrouaix** [comment]
I have an nice example incomming. and a few more thoughts. Can you wait until tomorrow ?

**Comment by jrouaix** [comment]
From this interaction in mind I made this quick and dirty complex example.
image
Here is the result :
image

**Comment by jrouaix** [comment]
I'm not satisfied with the result, i'll try with decorators.

**Comment by jrouaix** [comment]
Well I tried, but seems Props.ContextDecocator is not used, so I tried to implement the used ... and it's not that easy !

**Comment by rogeralsing** [comment]
I think we need to commit on how decorators should work, should they be chainable like middleware, is it enough to just have a single wrapper over the actor context?

**Comment by rogeralsing** [comment]
Context Decorators are working now:

https://github.com/AsynkronIT/protoactor-dotnet/blob/dev/examples/ContextDecorators/Program.cs

**Comment by jrouaix** [comment]
First results on decorator, now RequestAsync span is as long as the sum of all the process it will trigger
image

**Comment by jrouaix** [comment]
Will fix unit tests when api is more stable, now it's broken and it's a good reminder to udpate the tests.

**Comment by rogeralsing** [comment]
>Will fix unit tests when api is more stable, now it's broken and it's a good reminder to udpate the tests.

I didn't quite get this, is there anything I can/should do?

**Comment by jrouaix** [comment]
No i meant when the WithOpenTracing() stuffs are ok.
Do you have comments on what is done so far ?

**Comment by rogeralsing** [comment]
No I think it all looks great,
There seems to be some compile error that needs fixing first though:
```
OpenTracingExtensionsTests.cs(32,56): error CS1501: No overload for method 'OpenTracingSenderMiddleware' takes 2 arguments [C:\projects\protoactor-dotnet\tests\Proto.OpenTracing.Tests\Proto.OpenTracing.Tests.csproj]
    31 Warning(s)
    2 Error(s)
Time Elapsed 00:02:09.73
An error occurred when executing task 'Build'.
Error: One or more errors occurred.
	.NET Core CLI: Process returned an error (exit code 1).
```

**Comment by jrouaix** [comment]
Yes, of course, will do soon.

**Comment by rogeralsing** [comment]
I've merged it all in, but we need to fix those two failing tests for tracing

**Comment by jrouaix** [comment]
Yep, i'm on it here : https://github.com/jrouaix/protoactor-dotnet/tree/opentracing

**Pull request merged**
