### PR TITLE
Opentracing improvements

### PR DESCRIPTION
**Pull request by jrouaix**
@rogeralsing. Some more OpenTracing delivery. Could be enough to start using it (that i'll try on our projects next week using the myget prerelease packages)

Some frustration :
- Cannot decorate Context.Receive
  * so I can't fill the proto.actortype tag on the receive side
  * nor the proto.targetpid tag on the receive side (it should be easy, we are just on the target side :-|)

Tried some tricky changes : https://github.com/jrouaix/protoactor-dotnet/commit/28da2aa15f16cb1d1c16eab29ba997486001052e
No success so far on that part https://github.com/AsynkronIT/protoactor-dotnet/issues/409

### CODE REVIEW

**Comment by rogeralsing** [comment]
"Cannot decorate Context.Receive" 

How so?

`public virtual Task Receive(MessageEnvelope envelope)`

It's in there and should be possible to override?

**Comment by jrouaix** [comment]
Yes it's possible to override. Then when you do it, it's not called.

**Comment by rogeralsing** [comment]
Ok, Ill take a peek at that then. it should be invoked

**Comment by rogeralsing** [comment]
See https://github.com/AsynkronIT/protoactor-dotnet/issues/413

**Comment by jrouaix** [comment]
yep, thank you : https://github.com/AsynkronIT/protoactor-dotnet/pull/414

**Pull request merged**
