### PR TITLE
removed RecoveryStarted and Completed messages due to un-needed

### PR DESCRIPTION
**Pull request by raskolnikoov**
Due to new changes in the api (updatestate) we don't need to send messages for recoverystarted and recoverycompleted anymore.

### CODE REVIEW

**Comment by raskolnikoov** [comment]
Forgot to remove the messagetypes and cleanup example. Im gonna fix that when im home again.

**Comment by tomliversidge** [comment]
Do we not need them now? Can an actor receive new messages during recovery?

**Comment by raskolnikoov** [comment]
No the actor gets its first message (Started) after the recovery is finished.

**Comment by raskolnikoov** [comment]
Updated PR with some more missing cleanups in first commit.

**Comment by tomliversidge** [comment]
I'm a bit confused as to why the recent change has meant these events now need deleting - is it just that they are not useful / needed? The recent API change was from await ReceiveAsync to _actor.UpdateState, both being an essentially synchronous workflow, so I'm confused why this has affected RecoveryStarted and RecoveryCompleted

**Comment by raskolnikoov** [comment]
That's because RecoveryStarted/RecoveryCompleted used ReceiveAsync method and that messed up the context so the actor never got the "Started" message upon startup. They aren't needed since when the recover starts UpdateState is called with recovery data and awaited, then Startup gets passed to the actor and it should then have started with the "last state" it had upon shutdown/crash/earhquake.

**Comment by tomliversidge** [comment]
Ahh.. ok thanks for the explanation!

**Pull request merged**
