### PR TITLE
TO DISCUSS - Allow separate Event and Snapshot persistence to be used

### PR DESCRIPTION
**Pull request by tomliversidge**
Provided as an example - **please do not merge (yet).**

The rational behind this is that I might want to use a different persistence provider for snapshots vs events. For example, something like redis for snapshots, eventstore for events.

This is moving further away from the Go API though

### CODE REVIEW

**Comment by tomliversidge** [comment]
Issue to discuss persistence API here https://github.com/AsynkronIT/protoactor-dotnet/issues/137

**Comment by raskolnikoov** [comment]
Is this something we still want to implement now when we have rebuilt our persistence structure?

**Comment by tomliversidge** [comment]
The new persistence API still only supports a single store as it hasn't changed how iprovider or iproviderstore is implemented.

**Comment by tomliversidge** [comment]
I'm going to close this issue as there is an easier, more transparent way to do this based on recent refactorings

**Pull request closed without merging**
