### PR TITLE
Tests around persistence and an example persistent actor

### PR DESCRIPTION
**Pull request by tomliversidge**
Tests for main criteria around using actor persistence:

1. State can be rebuilt from events
2. State can be rebuilt from snapshots
3. State can be rebuilt from snapshot and subsequent events

Tests are done using an example persistent actor.

### CODE REVIEW

**Comment by raskolnikoov** [comment]
Great! Gonna have a look at it later.

**Comment by tomliversidge** [comment]
#117 clashes with this PR - if that one is merged first I can rebase this

**Comment by raskolnikoov** [comment]
@tomliversidge you can rebase this now since the ref pr is merged.

**Comment by tomliversidge** [comment]
OK, done - ready for merge / review

**Pull request merged**
