### PR TITLE
Automatically push to NuGet on push to master

### PR DESCRIPTION
**Pull request by cpx86**
This PR removes the dependency on me to publish master packages to the official NuGet feed 😅

### CODE REVIEW

**Comment by cpx86** [comment]
Oh, two things:
1. This hasn't been tested yet, for obvious reasons :)
2. Also changed the version pattern for pre-release so the build number precedes the branch name. That way the version ordering should be a bit more logical.

**Comment by cpx86** [comment]
Damnit, I broke something...

**Comment by cpx86** [comment]
There, now all seems to be well again :)

**Comment by adamhathcock** [comment]
Not sure if the PR detection should be passed in as a parameter or not.  Just feels weird to use that env var directly while the others are passed in.

Not a big deal though.

**Comment by cpx86** [comment]
Yeah that should be moved out.

**Comment by tomliversidge** [comment]
Is this good to merge?

**Comment by tomliversidge** [comment]
I squashed a lot of these commits @cpx86 hope you don't mind (you'll need to reset to remote locally if you work again on this branch)- trying to force another build on this branch

**Pull request merged**
