### PR TITLE
Simple scheduler with example

### PR DESCRIPTION
**Pull request by raskolnikoov**
New schedule structure after discussions on PR https://github.com/AsynkronIT/protoactor-dotnet/pull/95

### CODE REVIEW

**Comment by raskolnikoov** [comment]
SimpleSchedule works as an extension to IContext.

**Comment by rogeralsing** [comment]
I like this one, simple, just an extension, no fancy structures to hold the scheduler data. 
👍

**Comment by raskolnikoov** [comment]
@rogeralsing I changed my imlementation to not use this as an extension. So no more depencies for IContext, instead you pass the target (and if needed sender) PID's.

**Comment by tomliversidge** [comment]
Looks like this might need rebasing (and squashing?) - seems to have become a bit corrupted at some point as it is showing tests that are already in dev as being new - maybe from when the Proto.Router.Tests project was created at the root of the repo?

**Comment by raskolnikoov** [comment]
@tomliversidge yeah I fixed this a moment ago. Have a look at it again and then I'll merge.

**Comment by tomliversidge** [comment]
1. Tests? :) Would be interesting to try and test schedulers. Need to take away the time part somehow. 
2. This pull request has 13 commits - would look better in the history as 1 - "Add simple scheduler". I personally prefer to rebase and squash 
3. What else would implement ISimpleScheduler? I'm wondering if you need an interface for this.

What about the discussions in https://github.com/AsynkronIT/protoactor-dotnet/issues/97 around middleware and what to do when actors are stopped?

**Comment by raskolnikoov** [comment]
ping @tomliversidge 

1. Yeah this we need in the future, but for now I dont have any.
2. Yes I got my git skills poorly on this one. :)
3. I always try to implement to interfaces when coding. So for now no one else would implement to ISimpleScheduler I think. But it's nice to have.

**Comment by raskolnikoov** [comment]
Ready to merge if its okay by you other? ping @rogeralsing  @cpx86

**Comment by cpx86** [comment]
I'm a strong proponent of "merge early - change later". It's clean and provides value so let's not bikeshed it any more :)

**Pull request merged**
