### PR TITLE
System.Text.Json remote Serializer

### PR DESCRIPTION
**Pull request by Damian-P**
## Description

This PR allows to register a serializer that serializes registered IMessage types as protobuf and other types with System.Text.Json.

## Purpose
This pull request is a:

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist

- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added necessary documentation (if appropriate)

### CODE REVIEW

**Comment by rogeralsing** [comment]
Very cool! have you done any benchmarks if this affects e.g. remote benchmarks anything?
I'll try to review this fully during later today

**Comment by Damian-P** [comment]
When switching to the SystemTextJsonSerializer there is no noticeable performance impact on my computer (around 3M msg/s in the remote benchmark).
If the protobuf messages are not registered, then the performances in the remote benchmark are very poor comparing to the protobuf format. It gives me around 300k msg/s.

In the cluster benchmark, when not registering the protobuf messages it gives me 23k msg/s and 29k msg/s when they are registered.

The idea is to provide an abstract class with default protobuf serialization to serialize and deserialize all registered protobuf messages (especially the internal ones) and the user can then implement a custom serialization for other messages.

**Comment by rogeralsing** [comment]
Some thoughts here:
I'm a bit confused about the type hierarchy.

Why is it SystemTextJsonSerializer `: ProtobufSerializer`
and not `: ISerializer` ?

* It seems like it does not rely on anything in the base class
* it also seems to be a json serializer that can serialize any custom CLR type, not associated with the Protobuf Json format

Is it just a bit of bad naming of the base class, e.g. it's a ProtoActorSerializer, not a ProtobufSerializer ?

**Comment by Damian-P** [comment]
The base class relies on the implementation.

There is an explicit interface implementation that calls the protected abstract methods.
```c#
        object ISerializer.Deserialize(ByteString bytes, string typeName)
        {
            if (_serialization.TypeLookup.TryGetValue(typeName, out var parser))
                return parser.ParseFrom(bytes);
            return Deserialize(bytes, typeName);
        }
```
```c#
        protected abstract object Deserialize(ByteString bytes, string typeName);
```

The same concept applies to `GetTypeName()` and `Serialize()` so when the call is made to the serializer to deserialize a message, it tries to do his work in the interface implementation on the ProtobufSerializer class and if it can't handle the type then it passes the bytestring to the abstract method, here to the SystemTextJsonSerializer methods.

I have done this that way to keep the compatibility.

Users could then provide their own implementation of the ProtobufSerializer base class for the messages that the default serializer don't handle.

Of course we can rename the base class as you wish but it uses Protobuf so I though that it was a good name.
We can rename the DefaultProtobufSerializer to ProtoActorSerializer.

With this base class we can make the ISerializer internal and force users to rely on it to keep the internal messages being serialized with protobuf.

**Pull request closed without merging**
