### PR TITLE
testing webhook for CI

### PR DESCRIPTION
**Pull request by cpx86**

### CODE REVIEW

**Comment by cpx86** [comment]
OK so that didn't quite work... It's building both the source and target branch.

**Comment by cpx86** [comment]
@AsynkronIT/developers anyone with more AppVeyor experience than me who knows how to set this up properly? :)

**Comment by adamhathcock** [comment]
trying more fixes https://github.com/AsynkronIT/protoactor-dotnet/pull/260

**Comment by cpx86** [comment]
Hmm actually if the branches have diverged it makes sense to build both.

**Comment by cpx86** [comment]
But we'd want to be able to identify the build is from a PR so we don't publish NuGet packages

**Comment by adamhathcock** [comment]
I think I fixed that in the linked PR.  I moved the push step to the deploy stage which shouldn't run on a PR build.

**Comment by rogeralsing** [comment]
Should this one also be merged now that the other PR is in?

**Comment by cpx86** [comment]
This was just an empty commit to test the CI trigger. Closing.

**Pull request closed without merging**
