### PR TITLE
A Money Transfer Saga

### PR DESCRIPTION
**Pull request by tomliversidge**
An example of how to use Proto.Actor to implement a money transfer saga. This utilises the Behavior plugin, Persistence plugin and supervision so serves as an example for these. 

Not sure if the main repo is the best place for this, but I can move it if preferred. See the README for an extensive(!) description (this might be better going on the Proto.Actor blog? - i'm planning on publishing to my own blog at the least)

### CODE REVIEW

**Comment by raskolnikoov** [comment]
Yeah some blogging on our site would be nice to have!

**Comment by rogeralsing** [comment]
IF anyone wants to publish blogposts on the proto.actor web, here is where to do it:
https://github.com/AsynkronIT/gam-web/tree/master/src/blog

Or, it could be added as an article under the docs section:
https://github.com/AsynkronIT/gam-web/tree/master/src/docs

**Comment by tomliversidge** [comment]
Have published here https://medium.com/@tliversidge/https-medium-com-tliversidge-money-transfer-saga-part-1-7707e2b6f711 but can also publish on the blog and/or docs

**Comment by tomliversidge** [comment]
@rogeralsing how do the blog posts become visible? I added this https://github.com/AsynkronIT/gam-web/commit/73d6749eaf620ba1ab62a650b97bd5dfcda2c6d6
but it is not showing on the site - none of them are.
?

**Pull request merged**
