### PR TITLE
Redesigning process

### PR DESCRIPTION
**Pull request by rogeralsing**
Redesigning `Process`, removed Sender from API.
We already have `MessageEnvelope` which carries sender information,
previously the message envelope was created inside the local process.
Now it is created at the call site.
This is done to enable passing message headers together with the message and to eventually complete the outbound middleware.

In my machine the Router tests break now, I cant fint out why. 
Any router based example works fine, so I need to locate the issue before merging.

### CODE REVIEW

**Comment by rogeralsing** [comment]
Or is there an issue with the router tests that have been fixed recently?
The tests seems to fail silently here on the CI too.

cc @AsynkronIT/developers

**Comment by rogeralsing** [comment]
Any way to re-run tests?
It works locally now

**Comment by rogeralsing** [comment]
Ready for merge cc @AsynkronIT/developers 
Failed test is due to problem in Proto.Mailbox which haven't been changed in this PR.

**Comment by raskolnikoov** [comment]
:+1:

**Comment by cpx86** [comment]
LGTM :)

**Pull request merged**
