### PR TITLE
fix for perstistence context change

### PR DESCRIPTION
**Pull request by raskolnikoov**

### CODE REVIEW

**Comment by tomliversidge** [comment]
In other words, all PersistedEvent messages (aka state changes) need to be guaranteed to be applied before the next message is processed

**Comment by raskolnikoov** [comment]
ah I see.. so how can we achive that?

**Comment by raskolnikoov** [comment]
is it possible to set priority in the mailbox so these messages will be processed first?

**Comment by raskolnikoov** [comment]
or will this PR https://github.com/AsynkronIT/protoactor-dotnet/pull/172 fix this issue so the persistence api dosent need any changes?

**Comment by tomliversidge** [comment]
I wouldn't even go through the mailbox - if you see the option I provided in the issue it is just calling a new method I added to the IPersistantActor interface. The advantage is all state changes are processed synchronously from within the context of the received message.

**Comment by rogeralsing** [comment]
Agree with @tomliversidge, going through the mailbox is begging for issues.
e.g. if the replay fails, restarts and now some messages are left in the mailbox.
as we support async await we can safely do the init process as a sync flow

**Pull request closed without merging**
