### PR TITLE
Adding new ReceiveActor class that process messages using strongly ty…

### PR DESCRIPTION
**Pull request by Armando-GarzaTech**
@jakob-garzatech and I have a proposed solution to issue #87 that we would like to submit for your consideration.

### CODE REVIEW

**Comment by rogeralsing** [comment]
I'm all for having this kind of functionallity.
_But_, I would rather see it as a contrib extension.
The thing is that once you start adding inheritence to the mix, you get into all sorts of issues in terms of API evolution.

in Akka.NET, we had ReceiveActors, PersistentReceiveActors FsmActors, and a whole bunch of permutations of these combinations.
I would very much like to avoid this kind of scenario repeating in ProtoActor.

cc @AsynkronIT/developers

**Comment by raskolnikoov** [comment]
@rogeralsing I agree, keep it simple and let the developers add stuff if needed. :)

**Comment by Armando-GarzaTech** [comment]
I agree with no creating an extended API to handle our concern. I will close this pull request. 
However, we would be interested in starting a contrib extension. Is there a standard way to accomplish this or are we free to create something through Nuget?

Thanks - Armando

**Comment by adamhathcock** [comment]
I'm still not sure I even like mine.  The C# 7 pattern matching makes things nicer.  Though, I still would like strongly typed replies.  But that's my only real issue at the moment.

**Comment by Armando-GarzaTech** [comment]
@adamhathcock we decided to go with an implementation that didn't rely on inheritance and implemented the message routing in a helper class (MessageRouter). This way we could ensure that messages are typed when passed to a handler as well as providing multiple message routers that we can use to change actor behavior via a message. We felt that a fluent interface made the declaration of the handlers clear and easier to read.


    public class MessageRouter
    {
        private Func<IContext, Task> _otherwise;
        private readonly Dictionary<Type, Func<IContext, Task>> _whenHandlers
            = new Dictionary<Type, Func<IContext, Task>>();

        public MessageRouter When<T>(Func<T, IContext, Task> handler)
        {
            _whenHandlers.Add(typeof(T), context => handler((T)context.Message, context));
            return this;
        }

        public void Otherwise(Func<IContext, Task> handler)
        {
            _otherwise = handler;
        }

        public Task Handle(IContext context)
        {
            var messageType = context.Message.GetType();
            return _whenHandlers.ContainsKey(messageType)
                ? _whenHandlers[messageType](context)
                : _otherwise == null
                    ? Actor.Done
                    :_otherwise(context);
        }
    }

**SAMPLE ACTOR:**

    class MyTestActor : IActor
    {
        private readonly MessageRouter _router = new MessageRouter();

        public MyTestActor()
        {
	     _router
            .When<string>((msg, context) =>
            {
                context.Respond("string handled");
                return Actor.Done;
            })
            .When<int>(HandleInt)
            .Otherwise(context =>
            {
                context.Respond("otherwise handled");
                return Actor.Done;
            });
        }

        private Task HandleInt(int value, IContext context)
        {
            context.Respond(41 + value);
            return Actor.Done;
        }

        public Task ReceiveAsync(IContext context)
        {
            return _router.Handle(context);
        }
    }

**Comment by adamhathcock** [comment]
Thanks for the info.

However, that looks much more complex than the C# 7 switch case pattern matching.  Doing that is less characters, still strongly typed, and likely much more performant than your solution.  I would have done that before C# 7 but not now.

**Pull request closed without merging**
