### PR TITLE
Logging

### PR DESCRIPTION
**Pull request by adamhathcock**
Use a static log object.  Instrument some code and use an example.

I recognize this isn't what is discussed in: https://github.com/AsynkronIT/protoactor-dotnet/issues/18

Essentially, if I try to put an EventStream in I'll have to fan-in from all usages of `ILogger` (or some other interface) to the stream and put data in a custom `LogMessage`.  Then fan-out again to `ILogger` to allow usage of `ILoggerFactory` and all the logging implementations that use that.

Ideally, you want to use `ILogger` or `ILoggerFactory` directly in the code to be instrumented.  The problem was always how to get one of those objects to the code.

An event stream doesn't feel like a fit because the `LoggerFactory` itself is a pub/sub type construct in which all the implementations are subbing to the factory and the code is pubbing.

If this doesn't fit the vision at all, that's cool.  I guess I just don't see how log messages should be involved in an actual event stream.

### CODE REVIEW

**Comment by adamhathcock** [comment]
Closing in favor of https://github.com/AsynkronIT/protoactor-dotnet/pull/86

**Comment by adamhathcock** [comment]
@cpx86 reopened this.  

I have a static logger factory so we don't need to use DI.

I was wondering if the log should be moved to Proto.Mailbox or it's own project as Proto.Actor isn't the lowest level library.

**Comment by cpx86** [comment]
I think Proto.Actor is the best fit. The reason Mailbox is separate is because we want to make it possible to use Mailboxes for other purposes than Actors. But Proto.Actor is really the core library. Having a separate Proto.Logging feels a bit overkill since it probably wouldn't be usable outside of Proto.Actor.

**Comment by adamhathcock** [comment]
No problem.  Then I guess this is ready unless the style isn't liked.

**Pull request merged**
