### PR TITLE
NetCore 2.0

### PR DESCRIPTION
**Pull request by adamhathcock**
Added everything as NET Standard 2.0.  Dropped `net452` and `net461`  Marten doesn't build. 

I should probably multi-target net standards and `net452`?

Stuff might work if I just changed `netcoreapp1.1` to `netcoreapp2.0` only but not sure.  System packages would probably have be updated.  Microsoft.Extensions.* packages only target `netstandard2.0` now.

This is also a personal exercise to see how to deal with .NET Core 2.0 and bring forward other things properly.

### CODE REVIEW

**Comment by adamhathcock** [comment]
Looks like grpc needs some work on .net core 2.0 too.  Test results:

```
 System.AggregateException : One or more errors occurred. (Error loading native library. Not found in any of the possible locations: /Users/adam/code/new/protoactor-dotnet/tests/Proto.Remote.Tests/bin/Release/netcoreapp2.0/libgrpc_csharp_ext.x64.dylib,/Users/adam/code/new/protoactor-dotnet/tests/Proto.Remote.Tests/bin/Release/netcoreapp2.0/runtimes/osx/native/libgrpc_csharp_ext.x64.dylib,/Users/adam/code/new/protoactor-dotnet/tests/Proto.Remote.Tests/bin/Release/netcoreapp2.0/../../runtimes/osx/native/libgrpc_csharp_ext.x64.dylib) (The following constructor parameters did not have matching fixture data: RemoteManager remoteManager)
---- System.IO.FileNotFoundException : Error loading native library. Not found in any of the possible locations: /Users/adam/code/new/protoactor-dotnet/tests/Proto.Remote.Tests/bin/Release/netcoreapp2.0/libgrpc_csharp_ext.x64.dylib,/Users/adam/code/new/protoactor-dotnet/tests/Proto.Remote.Tests/bin/Release/netcoreapp2.0/runtimes/osx/native/libgrpc_csharp_ext.x64.dylib,/Users/adam/code/new/protoactor-dotnet/tests/Proto.Remote.Tests/bin/Release/netcoreapp2.0/../../runtimes/osx/native/libgrpc_csharp_ext.x64.dylib
---- The following constructor parameters did not have matching fixture data: RemoteManager remoteManager
Stack Trace:

----- Inner Stack Trace #1 (System.IO.FileNotFoundException) -----
   at Grpc.Core.Internal.UnmanagedLibrary.FirstValidLibraryPath(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.NativeExtension.Load()
   at Grpc.Core.Internal.NativeExtension..ctor()
   at Grpc.Core.Internal.NativeExtension.Get()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Server..ctor(IEnumerable`1 options)
   at Proto.Remote.Remote.Start(String hostname, Int32 port, RemoteConfig config) in /Users/adam/code/new/protoactor-dotnet/src/Proto.Remote/Remote.cs:line 53
   at Proto.Remote.Tests.RemoteManager..ctor() in /Users/adam/code/new/protoactor-dotnet/tests/Proto.Remote.Tests/RemoteManager.cs:line 22
----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----
```

**Comment by tomliversidge** [comment]
Is there any advantage to targeting net standard 2.0? Are there performance improvements?

**Comment by adamhathcock** [comment]
`netcoreapp2.0` does deliver more perf.  `netstandard2.0` is just a widening of the API surface.

I'm still trying to sort out what needs to be retargetted or what doesn't really.

**Comment by adamhathcock** [comment]
Redid things to leave targets as they were but only tests and examples were made `netcoreapp2.0`

GRPC definitely doesn't work.  I'm also thinking multi-targetting to `netstandard2.0` is probably the best way to go to support dependency changes (mainly Microsoft packages) if conflicts arise.

**Comment by joeblew99** [comment]
GRPC using .net standard 2.0 does not work yet. i also tried it on another project.

Someone else also asked about it here:
https://github.com/grpc/grpc/issues/12159

**Comment by joeblew99** [comment]
see here for GRPC:
 https://github.com/grpc/grpc/issues/12159

**Comment by joeblew99** [comment]
https://github.com/grpc/grpc/issues/12159

**Comment by joeblew99** [comment]
https://github.com/grpc/grpc/issues/12159

**Comment by joeblew99** [comment]
https://github.com/grpc/grpc/issues/12159

**Comment by rogeralsing** [comment]
cc @adamhathcock status on this one?

**Comment by adamhathcock** [comment]
Was waiting on grpc support.  Need to check the latest.

**Comment by adamhathcock** [comment]
Updated with some ideas I'm trying to Cake here: https://github.com/cake-build/cake/pull/1812

Namely, triple target: a 1.x standard, a net4x standard and 2.0 standard.  Tests are .net core 2 and net4x.  Could also be .net core 1 as well.

There is a mystery build error on some tests and RavenDB that need sorting.  RavenDB requires the 4.x lib which has API changes.

I can build Remote tests and get the same error
```
Failed   Proto.Remote.Tests.RemoteTests.CanSpawnRemoteActor
Error Message:
 System.AggregateException : One or more errors occurred. (Error loading native library. Not found in any of the possible locations: /Users/adam/git/personal/protoactor-dotnet/tests/Proto.Remote.Tests/bin/Debug/netcoreapp2.0/libgrpc_csharp_ext.x64.dylib,/Users/adam/git/personal/protoactor-dotnet/tests/Proto.Remote.Tests/bin/Debug/netcoreapp2.0/runtimes/osx/native/libgrpc_csharp_ext.x64.dylib,/Users/adam/git/personal/protoactor-dotnet/tests/Proto.Remote.Tests/bin/Debug/netcoreapp2.0/../../runtimes/osx/native/libgrpc_csharp_ext.x64.dylib) (The following constructorparameters did not have matching fixture data: RemoteManager remoteManager)
---- System.IO.FileNotFoundException : Error loading native library. Not found in any of the possible locations: /Users/adam/git/personal/protoactor-dotnet/tests/Proto.Remote.Tests/bin/Debug/netcoreapp2.0/libgrpc_csharp_ext.x64.dylib,/Users/adam/git/personal/protoactor-dotnet/tests/Proto.Remote.Tests/bin/Debug/netcoreapp2.0/runtimes/osx/native/libgrpc_csharp_ext.x64.dylib,/Users/adam/git/personal/protoactor-dotnet/tests/Proto.Remote.Tests/bin/Debug/netcoreapp2.0/../../runtimes/osx/native/libgrpc_csharp_ext.x64.dylib
---- The following constructor parameters did not have matching fixture data: RemoteManager remoteManager
Stack Trace:

----- Inner Stack Trace #1 (System.IO.FileNotFoundException) -----
   at Grpc.Core.Internal.UnmanagedLibrary.FirstValidLibraryPath(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.UnmanagedLibrary..ctor(String[] libraryPathAlternatives)
   at Grpc.Core.Internal.NativeExtension.Load()
   at Grpc.Core.Internal.NativeExtension..ctor()
   at Grpc.Core.Internal.NativeExtension.Get()
   at Grpc.Core.GrpcEnvironment.GrpcNativeInit()
   at Grpc.Core.GrpcEnvironment..ctor()
   at Grpc.Core.GrpcEnvironment.AddRef()
   at Grpc.Core.Server..ctor(IEnumerable`1 options)
   at Proto.Remote.Remote.Start(String hostname, Int32 port, RemoteConfig config) in /Users/adam/git/personal/protoactor-dotnet/src/Proto.Remote/Remote.cs:line 58
   at Proto.Remote.Remote.Start(String hostname, Int32 port) in /Users/adam/git/personal/protoactor-dotnet/src/Proto.Remote/Remote.cs:line 50
   at Proto.Remote.Tests.RemoteManager..ctor() in /Users/adam/git/personal/protoactor-dotnet/tests/Proto.Remote.Tests/RemoteManager.cs:line 20
----- Inner Stack Trace #2 (Xunit.Sdk.TestClassException) -----
```

GRPC has no proper support yet: https://github.com/grpc/grpc/issues/9441

**Comment by adamhathcock** [comment]
Apparently, this is an xunit issue.  When a new xunit version pops up on public feeds, I'll try again.

**Comment by rogeralsing** [comment]
👍

**Comment by adamhathcock** [comment]
Back on the case a bit.

**Comment by rogeralsing** [comment]
Does this mean we will have 1.5 2.0 and 452 all in the same nugets?

**Comment by adamhathcock** [comment]
Build passes!

@rogeralsing Yup!  There are some persistence things that need to be cleaned up or don't support .NET Standard 2.0 yet though.

I'm gonna go over the tests to make sure they run with the right packages and on `net452` at least

**Comment by adamhathcock** [comment]
Reviews of this PR can begin!

**Comment by rogeralsing** [comment]
That's fantastic, I was affraid we'd have to chose between 1.5 and 2.0 but if they work side by side, then it's all fine :)

**Comment by raskolnikoov** [comment]
@adamhathcock When I try to restore and build the solution on Visual Studio for Mac I get this error on Proto.Actor.

`Build started 2017-11-20 20:48:20.
__________________________________________________
Project "/Users/danielsoderberg/GIT/had-protoactor-dotnet/src/Proto.Actor/Proto.Actor.csproj" (Clean target(s)):

Target ReportAssetsLogMessages:
    /Users/danielsoderberg/GIT/had-protoactor-dotnet/src/Proto.Actor/Proto.Actor.csproj : error NU1202: Package Microsoft.Extensions.Logging.Abstractions 2.0.0 is not compatible with netstandard1.5 (.NETStandard,Version=v1.5). Package Microsoft.Extensions.Logging.Abstractions 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
    Build continuing because "ContinueOnError" on the task "ReportAssetsLogMessages" is set to "ErrorAndContinue".
Done building target "ReportAssetsLogMessages" in project "Proto.Actor.csproj" -- FAILED.
Target _GetProjectReferenceTargetFrameworkProperties:
    __________________________________________________
    Project "/Users/danielsoderberg/GIT/had-protoactor-dotnet/src/Proto.Actor/Proto.Actor.csproj" is building "/Users/danielsoderberg/GIT/had-protoactor-dotnet/src/Proto.Mailbox/Proto.Mailbox.csproj" (GetTargetFrameworkProperties target(s)):


Done building project "Proto.Actor.csproj" -- FAILED.

Build FAILED.

/Users/danielsoderberg/GIT/had-protoactor-dotnet/src/Proto.Actor/Proto.Actor.csproj : error NU1202: Package Microsoft.Extensions.Logging.Abstractions 2.0.0 is not compatible with netstandard1.5 (.NETStandard,Version=v1.5). Package Microsoft.Extensions.Logging.Abstractions 2.0.0 supports: netstandard2.0 (.NETStandard,Version=v2.0)
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.08`

**Comment by raskolnikoov** [comment]
@adamhathcock everything seems to work when I run the solution on windows using Visual Studio.

**Comment by adamhathcock** [comment]
No issues on my VS for Mac.  I usually just use VSCode and the CLI though.

**Comment by raskolnikoov** [comment]
I only have issues on my Mac when I build the whole solution. If I build an example app then it works.

**Comment by adamhathcock** [comment]
@raskolnikoov I was dumb and was opening the wrong solution :(

The issue with Proto.Mailbox on the mac is that `net452` needs to be configured correctly.  The Cake script does this but VS for Mac itself doesn't.  I'm not worried about it as it's a Full Framework target and the tests pass on windows.

**Comment by raskolnikoov** [comment]
@adamhathcock lets go then  :)

**Comment by adamhathcock** [comment]
I'll let someone else besides me review and merge :)

**Comment by silentnull** [comment]
Hi. Why persistance provider are part of main Proto.Actor project ? Maybe is better solution toove these as separeted projects. Still only in memory provider. That is in Proto.Actor Go projects and Akka.NET.

**Comment by adamhathcock** [comment]
I'm going to merge this soon unless someone objects

**Comment by adamhathcock** [comment]
@AsynkronIT/developers I'm going to merge this soon unless someone objects

**Pull request merged**
