### PR TITLE
RootContext / ActorClient RequestAsync implemented

### PR DESCRIPTION
**Pull request by jrouaix**
@rogeralsing following the discussion on gitter.im.
RequestAsync on ActorClient is implemented in this PR. 
IMO the SendUserMessage method (i copied from LocalContext) should be factorised. Have you a preference about where I should put it ?

### CODE REVIEW

**Comment by rogeralsing** [comment]
Very Nice!

**Comment by jrouaix** [comment]
I have some other changes incomming

**Comment by jrouaix** [comment]
Moving some IContext function into ISenderContext, to have the same "send" api in ActorClient than in LocalContext.

``` csharp
public interface ISenderContext
    {
        object Message { get; }

        MessageHeader Headers { get; }

        void Tell(PID target, object message);

        void Request(PID target, object message);
        Task<T> RequestAsync<T>(PID target, object message, TimeSpan timeout);
        Task<T> RequestAsync<T>(PID target, object message, CancellationToken cancellationToken);
        Task<T> RequestAsync<T>(PID target, object message);
    }
```

**Comment by cpx86** [comment]
👍

**Pull request merged**
